language: objective-c
osx_image: xcode11.6
xcode_project: DateToolsObjC.xcodeproj
xcode_scheme: DateToolsObjC
env:
  global: FRAMEWORK_NAME=DateToolsObjC
before_script:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - gem install xcpretty
  - gem install xcpretty-travis-formatter
script:
  - xcodebuild -project DateToolsObjC.xcodeproj -scheme DateToolsObjC -configuration Release test | xcpretty
before_deploy:
  - carthage build --no-skip-current
  - carthage archive $FRAMEWORK_NAME
deploy:
  provider: releases
  api_key:
    secure: C638ULZfOxwTxt4MaNBgiFYF912M947L9OlPhkFVvdlYSF5xNAwzQo71ppKOudIvtSnaIDiR0EMp/qWn+bo0UWfRwsFCCeHhf1JsDQQ6P9DloDfZr+HLrRvMAt8osLlIUHDaW+6oBIJtEJwYS3cFxM6ZhpsWWWdpkit5zD6Rf18wL2HqjXubpA1qseX4hg/XeOMd00sNjjhiLWiBtB8RUpUWYOR6yKt/Zec5qWFsc46KsUlcku+wmiHaFrgEissfkPNEyENgTp42MxjoAkF1TsKHSgXg071yK7NbUuNX+j2QPql1khucZ2sii2Ko4hNyATxSoNBHrjNmXlB9ouFUUslnZm+L6VnO1o3FejTegmqZSSw1PNZrwrrAWesE49hbfEUPwG+YWG7MhI7u3RuWvSFc7kgErWQR+psyxbZn97tQ+hZ+EVwPlqSmi2IfyjG91Lg7LqENHxWbFLE3mYqVaHmgYeOD5opaw9RSJv6fRZwgAdsRCk1mkRRCVC6kNLqY5Qpyn3c57wbsdLJWZR/Rea0WO5uUN08fNLiaGhbRXo8rdyWD5noP2nccrV7yozAr33grXtSI7dcViu8AU4YXoqxRFZkvtbHjjB/f2R5P8qb66e/OdOEbXfPeD1Epuo8smSzfTV7WNDxGaYkK0hoduMuJwIvi1QGKtLWw3iiQK8M=
  file: "$FRAMEWORK_NAME.framework.zip"
  skip_cleanup: "true"
  on:
    repo: 3a4oT/DateToolsObjC
    tags: true

