name: CI
on:
  pull_request:
    paths:
      - ".github/workflows/CI.yml"
      - "Sources/*"
      - "Tests/*"

jobs:
  SPM-Build:
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.6.app/Contents/Developer
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Verify that DateToolsObjC can be build by SPM
        run: xcrun swift build
  iOS-Xcode:
    name: Test iOS
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.6.app/Contents/Developer
    strategy:
      matrix:
        destination: ["OS=13.6,name=iPhone 11 Pro"] #, "OS=12.4,name=iPhone XS", "OS=11.4,name=iPhone X", "OS=10.3.1,name=iPhone SE"]
    steps:
      - uses: actions/checkout@v2
      - name: iOS - ${{ matrix.destination }}
        run: xcodebuild -project "DateToolsObjC.xcodeproj" -scheme "DateToolsObjC" -destination "${{ matrix.destination }}" clean test | xcpretty
  iOS14-Xcode:
    name: Test iOS 14
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_12_beta.app/Contents/Developer
    strategy:
      matrix:
        destination: ["OS=14.0,name=iPhone 11 Pro"] #, "OS=12.4,name=iPhone XS", "OS=11.4,name=iPhone X", "OS=10.3.1,name=iPhone SE"]
    steps:
      - uses: actions/checkout@v2
      - name: iOS - ${{ matrix.destination }}
        run: xcodebuild -project "DateToolsObjC.xcodeproj" -scheme "DateToolsObjC" -destination "${{ matrix.destination }}" clean test | xcpretty
  tvOS-Xcode:
    name: Test tvOS
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.6.app/Contents/Developer
    strategy:
      matrix:
        destination: ["OS=13.4,name=Apple TV 4K"] #, "OS=11.4,name=Apple TV 4K", "OS=10.2,name=Apple TV 1080p"]
    steps:
      - uses: actions/checkout@v2
      - name: tvOS - ${{ matrix.destination }}
        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -project "DateToolsObjC.xcodeproj" -scheme "DateToolsObjC" -destination "${{ matrix.destination }}" clean test | xcpretty
  watchOS-Xcode:
    name: Build watchOS
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.6.app/Contents/Developer
    strategy:
      matrix:
        destination: ["OS=6.2.1,name=Apple Watch Series 5 - 44mm"] #, "OS=4.2,name=Apple Watch Series 3 - 42mm", "OS=3.2,name=Apple Watch Series 2 - 42mm"]
    steps:
      - uses: actions/checkout@v2
      - name: watchOS - ${{ matrix.destination }}
        run: xcodebuild -project "DateToolsObjC.xcodeproj" -scheme "DateToolsObjC" -destination "${{ matrix.destination }}" clean build | xcpretty
